version: '3.3'
services:
  carango-bom:
    build:
      dockerfile: 'Dockerfile'
      context: './'
    image: carango-bom-api-grupo-5
    container_name: carango-bom-api
    ports: 
      - '8080:8080'
    expose:
        - '8080'
    networks:
      - carango-bom-network
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/carangobom
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
      - PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'carangobom'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '123'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - carango-bom-network
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
networks:
  carango-bom-network: 